{{- if .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mini-app-route
  labels:
    app: mini-app
spec:
  parentRefs:
    - name: mini-app-gateway
  rules:
    {{- range .Values.gatewayApi.routes }}
    - matches:
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
      {{- if .rewrite }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      {{- end }}
      backendRefs:
        - name: {{ .backendService }}
          port: {{ .backendPort }}
    {{- end }}
{{- end }}