apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mini-app-netpol
  labels:
    app: mini-app
spec:
  podSelector:
    matchLabels:
      app: mini-app
  policyTypes:
    - Ingress
  ingress:
    
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 80
  