{{- if .Values.tls.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniapp-tls-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.tls.secretStoreName }}
  target:
    name: {{ .Values.tls.secretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: miniapp-tls-crt
    - secretKey: tls.key
      remoteRef:
        key: miniapp-tls-key
{{- end }}